MyBundles\MyTestBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        userName:
            type: string
            length: 10
        password:
            type: string
            length: 20
        name:
            type: string
            length: 60